services:
  app:
    build: .
    container_name: my_app_container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
